# Check that interpreter is correct

In [1]:
import sys
sys.executable

'C:\\Users\\hunte\\Anaconda3\\python.exe'

# Argument passing to function 
## mutable / immutable types

In [2]:
x = 10
def f(x):
    x = 5
f(x)
print(x)

10


In [3]:
x = 10
def f(x):
    x += 5
f(x)
print(x)

10


In [4]:
l = [1,2,3]
def f(l):
    l = [4]
f(l)
print(l)

[1, 2, 3]


In [5]:
l = [1,2,3]
def f(l):
    l += [4]
f(l)
print(l)

[1, 2, 3, 4]


## Numpy features

In [6]:
import numpy as np

## Assignment of objects

In [7]:
x = np.zeros((2,3,4))
y = x
x[0][0][0]=100
print(x)
print(y)

[[[100.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]]

 [[  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]]]
[[[100.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]]

 [[  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]]]


In [8]:
x = np.zeros((2,3,4))
y = x.copy()
x[0][0][0]=100
print(x)
print(y)

[[[100.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]]

 [[  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Slicing

In [9]:
x = np.arange(25).reshape(5,5)
print(x)
y = x[:3, :4]
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [10]:
y = x[2:5, 2:4]
print(y)

[[12 13]
 [17 18]
 [22 23]]


In [11]:
y = x[0:5:2, 0:5:2]
print(y)

[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


## Use of boolean arrays

In [12]:
x = np.random.rand(30).reshape(5,6)
print(x)
x[x>0.5]=0
print(x)

[[0.94082593 0.9287777  0.70766278 0.45924989 0.71446365 0.36509256]
 [0.27895657 0.32700991 0.68111973 0.46134222 0.09235272 0.35299255]
 [0.49649625 0.89174094 0.50377289 0.51814084 0.99187396 0.59668797]
 [0.60102831 0.21141819 0.01022515 0.7934296  0.82153561 0.01618999]
 [0.21869401 0.43938994 0.81462102 0.84051271 0.92419082 0.00138969]]
[[0.         0.         0.         0.45924989 0.         0.36509256]
 [0.27895657 0.32700991 0.         0.46134222 0.09235272 0.35299255]
 [0.49649625 0.         0.         0.         0.         0.        ]
 [0.         0.21141819 0.01022515 0.         0.         0.01618999]
 [0.21869401 0.43938994 0.         0.         0.         0.00138969]]


## Vectorization

In [13]:
N= 10**7
x = np.random.rand(N)
y = np.random.rand(N)

In [14]:
import time
timeStart = time.time()
ip = 0
for i in range(N):
    ip += x[i]*y[i]
duration = time.time() - timeStart
print(duration)
print(ip)

11.085146188735962
2500095.01913149


In [15]:
timeStart = time.time()
ip = np.dot(x,y)
duration = time.time() - timeStart
print(duration)
print(ip)

1.982774019241333
2500095.0191316884


## Ways to multiply matrices

In [16]:
x = np.arange(100).reshape(2, 50)
y = np.arange(100).reshape(50, 2)

In [17]:
print(x.dot(y))
print(x @ y)
print(np.einsum("ik,kj->ij", x, y))

[[ 80850  82075]
 [203350 207075]]
[[ 80850  82075]
 [203350 207075]]
[[ 80850  82075]
 [203350 207075]]


## Broadcasting

In [22]:
x = np.linspace(0, 10, num=5)
print(x)
y = np.linspace(0, 20, num=4)
print(y)
print(x.reshape(5, 1) + y.reshape(1, 4))

[ 0.   2.5  5.   7.5 10. ]
[ 0.          6.66666667 13.33333333 20.        ]
[[ 0.          6.66666667 13.33333333 20.        ]
 [ 2.5         9.16666667 15.83333333 22.5       ]
 [ 5.         11.66666667 18.33333333 25.        ]
 [ 7.5        14.16666667 20.83333333 27.5       ]
 [10.         16.66666667 23.33333333 30.        ]]


## Nearest neighbor on subset of MNIST

In [23]:
train_data = np.genfromtxt("mnist_train.csv", delimiter=',')
test_data = np.genfromtxt("mnist_test.csv", delimiter=',')

In [24]:
print(train_data.shape)
print(test_data.shape)

(60000, 785)
(10000, 785)


In [25]:
N_train = 1000
N_test = 100
train_labels = train_data[:N_train, 0].astype(int)
train_images = train_data[:N_train, 1:]
test_labels = test_data[:N_test, 0].astype(int)
test_images = test_data[:N_test, 1:]

In [26]:
print(train_labels.shape)
print(train_images.shape)
print(test_labels.shape)
print(test_images.shape)

(1000,)
(1000, 784)
(100,)
(100, 784)


In [75]:
a = test_images[1,:]
print(a.shape)
print((a-train_images).shape)

(784,)
(1000, 784)


In [82]:
a = np.arange(18).reshape(6, 3)
b = np.arange(12).reshape(4, 3)
c = b[0, :]
print(a)
print(c)
print(c - a)
print((c-a).sum(axis = 1))
A = (c-a).sum(axis = 1)
print(A.argmin(axis = 0))
#print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[0 1 2]
[[  0   0   0]
 [ -3  -3  -3]
 [ -6  -6  -6]
 [ -9  -9  -9]
 [-12 -12 -12]
 [-15 -15 -15]]
[  0  -9 -18 -27 -36 -45]
5


In [30]:
print((a-b).shape)

(6, 4, 3)


In [31]:
print(a-b)

[[[ 0  0  0]
  [-3 -3 -3]
  [-6 -6 -6]
  [-9 -9 -9]]

 [[ 3  3  3]
  [ 0  0  0]
  [-3 -3 -3]
  [-6 -6 -6]]

 [[ 6  6  6]
  [ 3  3  3]
  [ 0  0  0]
  [-3 -3 -3]]

 [[ 9  9  9]
  [ 6  6  6]
  [ 3  3  3]
  [ 0  0  0]]

 [[12 12 12]
  [ 9  9  9]
  [ 6  6  6]
  [ 3  3  3]]

 [[15 15 15]
  [12 12 12]
  [ 9  9  9]
  [ 6  6  6]]]


In [43]:
M = (a-b).sum(axis = 2)
M

array([[  0,  -9, -18, -27],
       [  9,   0,  -9, -18],
       [ 18,   9,   0,  -9],
       [ 27,  18,   9,   0],
       [ 36,  27,  18,   9],
       [ 45,  36,  27,  18]])

In [48]:
M.argmin(axis = 0)

array([0, 0, 0, 0], dtype=int64)

In [61]:
def ClassifyImages(train_images, train_labels, test_images):
    Tr = train_images.reshape(N_train, 1, 784)
    Te = test_images.reshape(1, N_test, 784)
    #print((Tr - Te).shape)
    DM = np.square(Tr - Te).sum(axis = 2)
    #print(DM.shape[0])
    index = DM.argmin(axis = 0)
    '''print(index.shape)
    print(index)
    print(train_labels.shape)
    print(train_labels)
    print(train_labels[index])'''
    return train_labels[index]

In [68]:
test_predicted = ClassifyImages(train_images, train_labels, test_images)
print(test_predicted[:16])
print(test_labels[:16])

(1000, 100, 784)
[7 2 1 0 4 1 9 9 4 9 0 6 9 0 1 3]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5]


In [70]:
print((test_predicted[:16] == test_labels[:16]))

[ True  True  True  True  True  True False  True False  True  True  True
  True  True  True False]


In [69]:
accuracy = (test_predicted[:16] == test_labels[:16]).sum()
print(accuracy)

13
